name: myTestWorkFlow

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "Hello script"

      - name: List files in the repository
        run: |
          echo "The repository ${{github.repository}} contain the following files:"
          tree
      
    
