name: myTestWorkFlow

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello script"

      - name: Checkout
      - uses: actions/checkout@v4
      
    
